[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

; Match the "ATmega328P" (New Bootloader) setting from Arduino IDE
upload_speed = 115200

; Recommended for debugging and serial communication
monitor_speed = 115200
monitor_filters = time, colorize

lib_deps =
    arduino-libraries/Servo @ ^1.2.2
